# Generated by Django 5.1 on 2025-03-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='assigned_doctor',
        ),
        migrations.AddField(
            model_name='patient',
            name='assigned_doctors',
            field=models.ManyToManyField(blank=True, to='users.doctor'),
        ),
    ]
